name: apiarium
description: "Apiarium mobile app for beekeepers"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  go_router: ^15.1.2
  flutter_bloc: ^9.1.1 
  google_fonts: ^6.2.1
  easy_localization: ^3.0.7+1
  envied: ^1.1.1
  path: ^1.9.1
  meta: ^1.16.0
  bloc: ^9.0.0
  equatable: ^2.0.7
  uuid: ^4.5.1
  dropdown_button2: ^2.3.9
  flutter_reorderable_grid_view: ^5.5.0
  logger: ^2.5.0
  flutter_tts: ^4.2.3 
  fluttertoast: ^8.2.12
  get_it: ^8.0.3
  path_provider: ^2.1.5
  
  
  # Firebase
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.8
  
  # RevenueCat
  purchases_flutter: ^8.10.2

  # Google Maps
  google_maps_flutter: ^2.12.3
  geocoding: ^4.0.0

  #Hive CE
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.1

  #Shared Preferences and Secure Storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

  # Image Picker
  image_picker: ^1.1.2
  
  vosk_flutter:
    git:
      url: https://github.com/alphacep/vosk-flutter.git
      ref: e655a96
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.3.5

  envied_generator: ^1.1.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/text_data/name_generator.json
    - assets/text_data/voice_grammar.json
