name: apiarium
description: "Apiarium mobile app for beekeepers"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.8.0
  flutter_bloc: ^9.1.0
  google_fonts: ^6.2.1
  easy_localization: ^3.0.7+1
  envied: ^1.1.1
  sqflite: ^2.4.2
  path: ^1.9.1
  supabase_flutter: ^2.8.4
  meta: ^1.16.0
  bloc: ^9.0.0
  equatable: ^2.0.7
  uuid: ^4.5.1
  dropdown_button2: ^2.3.9
  flutter_reorderable_grid_view: ^5.5.0
  logger: ^2.5.0
  vosk_flutter:
    git:
      url: https://github.com/alphacep/vosk-flutter.git
      ref: e655a96
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  sqflite_common_ffi: ^2.3.5

  envied_generator: ^1.1.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/
    - assets/data/name_generator.json
